name: Build C++

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
 build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        vcpkg integrate install
        vcpkg install tinyxml2
        vcpkg install libzippp


    - name: Build Solution
      run: msbuild Charcoal/Charcoal.sln /p:Configuration=Debug
